### PR TITLE
Finalizing large pull request

### PR DESCRIPTION
**Pull request by th-we**
One last review?  Merging went smoothly without conflicts or failing tests.

This PR is mainly documentation and some changes that I found sensible while writing documentation.

### CODE REVIEW

**Comment by annplaksin** [comment]
Did you try to merge this already with my other PR?

**Comment by th-we** [comment]
I hate to merge failing test ;-). I'll have a look at it and add it to the other pull request.

**Comment by annplaksin** [comment]
Then comment the failing test out ;-) ... I was hoping that adding multiple fermatas might be something quick, but nope

**Comment by annplaksin** [comment]
I commented it out... 🤪

**Review by annplaksin — APPROVED** [review]
Without testing it myself (I am obviously trusting you on that), that PR looks amazing. 
Thanks!

Would you like to merge?

**Comment by th-we** [comment]
I'll also include the fermata stuff. I cherry-picked your fermata commits and made it work, but right now libmei for some reason fails to serialize. I'll sort that out.

And there's one more thing I'll fix:  The default file name and path should be set to the name and path of the sib file, but right now the path is not set and the default filename has a sib extension instead of an mei extension. That really annoys me.

**Comment by th-we** [comment]
O.K., done. I'd be really happy if you could take it for a test drive, @annplaksin!

**Comment by annplaksin** [comment]
I checked it out and ran the tests. 114 passing,...
Looks like it works and we're happy to merge. 🙂

**Comment by th-we** [comment]
Awesome!

I also added some testing goodies, fixing the accidentals.sib hiccup and triggering mocha from within ManuScript, if you create a `*.bat` file for that.

I realize I can't do the pull request from this repo because I simply pushed it here instead of forking.  Because it's not really useful if it can't interact with the upstream repo, I will delete this repo later.  If there's anything that you want (me) to do before deletion, let me know.

**Comment by annplaksin** [comment]
So many goodies! It sounds like Christmas... awesome! 😄 
Nope, that's the problem with not forking. And creating a new remote afterwards won't help either in Github as far as I know.

I am not quite sure what should have happened when clicking on the extension test in the Plugin menu, because nothin happens. But the Test runner contains the extension test anyway.
If you know, what the purpose of the menu entry was, I would be glad.
Apart from that, deleting is fine with me.

**Comment by th-we** [comment]
You mean "Sibmei extension test"? The problem with the test extension is [this](https://github.com/th-we/sibmei/blob/3423443b42f1bd8be1d26e84c08561d79c55552b/lib/sibmei4_extension_test.plg#L5):
```
AddToPluginsMenu('Sibmei extension test', null);
```
It does not have a "Run" method itself because Sibmei serves as the hub for exporting.  So there's nothing to run.

That might be a flaw we should fix.  Maybe define the extension name somewhere else instead of using the usual mechanism with `AddToPluginsMenu()`?  That would prevent it from appearing in the menu.  A global variable could be used instead, just like for `SibmeiExtensionAPIVersion`.

**Comment by annplaksin** [comment]
Defining the name in the usual manner is okay, I think.And having it in the menu seems good to me as well, because a user can see if the extension plugin is there and available. But yes, clicking and nothing happens isn't cool.
How about adding a short `Run()` method opening a popup message like "This plug-in is an extension of sibmei. Please run MEI export.".

**Comment by th-we** [comment]
We won't deliver the test extension to end users, so there's no big problem. But the test plugin also serves as reference, so it's a good idea to establish a proper way of doing things.

Another thing that I realize now is that the extension selection dialog will only be shown the first time sibmei is run in each session. That should definitely be fixed.

**Comment by th-we** [comment]
Or am I mistaken because I messed with my code? Checking now...

**Comment by th-we** [comment]
O.K., my mistake – works as expected. I'll add a message to the example extension per your suggestion.

**Comment by annplaksin** [comment]
Quak! 🦆

**Comment by annplaksin** [comment]
I am just testing it. That's great 🙂

**Comment by th-we** [comment]
Continuing [here](https://github.com/music-encoding/sibmei/pull/162).

**Pull request closed without merging**
